language: rust
cache: cargo
dist: trusty

os:
  - linux
  - osx
  - windows

rust:
  - stable

script:
  - cargo build --release
  - cargo test --no-fail-fast ||
    (
      echo 'initial `cargo test` failed, retrying with fewer cores to work around OOM issues' &&
      cargo test --no-fail-fast --verbose -j 1
    )

deploy:
  provider: releases
  api_key:
    secure: "YxV4yVCn8x4F8bFKbMMX4WpGGkIu8yTjWzz+mFqGw5+nVtJ3ptr52LkZWXbJDLWoQEissRr89vDMJ3q+bCGL+lnyWyyhkn7m18ruIYysYJ+tRwqhCMshD968wclbYMTKdQoMPIuhsQtb+EEIBO+lERdq3VFTGLC0UHpy2m53qY5SYgYSRJP8kJTUKHS479JHRJKxqYNVYrib1u3qVmt1G9SW4SG1NB66HBkZ2HTNP7eSmlJe9K41Js6IBQdOhLCABZ3eNRV3HYZ8Ar6lUv8brQOuyLI3g98cQIa4KwKsjodD2O5AT73vV255wNutGYzbgP8/jHbDBnd1zSIlM7jM4VtoquQ0jpeJTV6sveSPYXfFBzWZ/bl9JtXWqENxJ+CUMSKnPj0HhkA38qnXdz9EVtzbr08BYlDaX8QM69o0NeIu6ODp1Ab7E94im95ghVSTwp2VzSnZXO+hAIHnxaKHZfmHoeFlUCUViQHqXbj5VsozW2hR7kuoFWdoitx+3rCjOYEC8tEXwXPjWOqEuKEocXVK/bptn4ylO0qDc9ycZZnLmT6XXAfE4NFMqMnpb651ha1C+JOHe464MLD/uCyQWnjWENcJ3/U1d4ebVhenyr3ZXWI6KyYXdYBLVCX1MTW3apoFMdbDlnHvHRKiVy7Lefd+fSh5zMw5h2Dt5zMExcE="
  file_glob: true
  file: target/release/midi2spc*
  name: $TRAVIS_OS_NAME-$TRAVIS_BUILD_NUMBER
  skip_cleanup: true
  draft: true