[package]
name = "midi2spc"
version = "0.1.0"
authors = ["Gus Prevas <kprevas@gmail.com>"]

[dependencies]
ghakuf = "0.5.1"
snes-spc = { git = "https://github.com/elizagamedev/rust-snes-spc" }
clap = "2.29.0"
itertools = "0.7.8"
byteorder = "1.2.7"
serde = "1.0.80"
serde_json = "1.0"
serde_derive = "1.0.80"
failure = "0.1.5"