[package]
name = "nsasm"
version = "0.1.0"
authors = ["Gus Prevas <kprevas@gmail.com>"]
edition = "2018"

#[lib]
#path = "fake_lib.rs"

[dependencies]
itertools = "0.8.0"

[raze]
workspace_path = "//nsasm/cargo"
genmode = "Remote"
target = "x86_64-unknown-linux-gnu"